version: "3.8"

services:

  # image 1 (mysql db)
  mysql:
    image: mysql:8
    container_name: mysql_db_docker
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: scm2025
    ports:
      - "33306:3306"

    volumes:
      - ./mysql_data:/var/lib/mysql # data which is present in container at location /var/lib/mysql will also be
      # coming at ./mysql_data our host PC location

  # image 2 (phpmyadmin UI)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_my_admin_docker
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8081:80"
    depends_on:
      - mysql

  # image 3 (springboot app)
  springboot:
    build: . # dot meaning build from current directory docker file
    container_name: SCM_Springboot_Project
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: scm2025
      MYSQL_USER: root
      MYSQL_PASSWORD: root1998
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USERNAME: smtp@mailtrap.io
      EMAIL_PASSWORD: 8a5358f935bbf7e5271ca1ddc5254839
      CLOUDINARY_API_KEY: 451172475223473
      CLOUDINARY_API_SECRET: wpzpdpq-y6lVzC0FFvzx6Xuqcw0
      CLOUDINARY_NAME: dljugu2i1
    ports:
      - "8082:8080"
    depends_on:
      - mysql
volumes:
  mysql_data: {}